theme: jekyll-theme-cayman
title: This Page is Stupid. Please Leave Now.
Feel free to ignore this page, as there is no point to it. Much like everything we do.

I work on a tv show about mentally ill people.  Sometimes when I've been standing in piles of garbage getting yelled at by crazy
people and I'm in my 16th hour of the day, I get demoralized.  Then I think, what the hell else am I going to do?
